#define mySizeOf(v) (sizeof(v) / sizeof(v[0]))

#define LCD_WIDTH 240
#define LCD_HEIGHT 400
#define PIXEL_PER_BYTE 2

#define ROM_ADDRESS 0x1000000

#define STACK_ADDRESS 0x2000000

#define VM_Manager_Table_ADDRESS 0x3000000
#define VM_FUNC_HK_TABLE_ADDRESS 0x4000000

#define VM_Memory_Pool_ADDRESS 0x5000000
#define VM_MEMPOOL_TOTAL_SIZE 0x1000000
#define VM_MemoryBlock_SIZE 0x400000 // 4MB 真机是0x14000
#define VM_MemoryBlock_PTR_ADDRESS (VM_Memory_Pool_ADDRESS + VM_MemoryBlock_SIZE)
#define VM_screenImageStruct_ADDRESS (VM_MemoryBlock_PTR_ADDRESS + 512)
#define VM_screenImage_ADDRESS (VM_screenImageStruct_ADDRESS + 8)
#define VM_screenImage_End_ADDRESS (VM_screenImage_ADDRESS + LCD_WIDTH * LCD_HEIGHT * LCD_PITCH)

// 0x3000000开始是函数表地址
#define VM_MANAGER_TABLE_SIZE 0x400
#define VM_MANAGER_TABLE_ADDRESS (VM_Manager_Table_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_SYS_MANAGER_TABLE_ADDRESS (VM_MANAGER_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MEMORY_MANAGER_TABLE_ADDRESS (VM_SYS_MANAGER_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_GAMEOLD_TABLE_ADDRESS (VM_MEMORY_MANAGER_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_LCD_TABLE_ADDRESS (VM_MANAGER_GAMEOLD_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_FILEIO_TABLE_ADDRESS (VM_MANAGER_LCD_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_STDIO_TABLE_ADDRESS (VM_MANAGER_FILEIO_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_TIMER_TABLE_ADDRESS (VM_MANAGER_STDIO_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_CTRL_TABLE_ADDRESS (VM_MANAGER_TIMER_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_NETWORK_TABLE_ADDRESS (VM_MANAGER_CTRL_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_GAME_UTIL_TABLE_ADDRESS (VM_MANAGER_NETWORK_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_DF_ENGINE_TABLE_ADDRESS (VM_MANAGER_GAME_UTIL_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_BILLING_TABLE_ADDRESS (VM_MANAGER_DF_ENGINE_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_UCS2_TABLE_ADDRESS (VM_MANAGER_BILLING_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_SCREEN_TABLE_ADDRESS (VM_MANAGER_UCS2_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_DF_SCRIPT_TABLE_ADDRESS (VM_MANAGER_SCREEN_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_GAME_LCD_TABLE_ADDRESS (VM_MANAGER_DF_SCRIPT_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_NETAPP_TABLE_ADDRESS (VM_MANAGER_GAME_LCD_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_AUDIO_TABLE_ADDRESS (VM_MANAGER_NETAPP_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_SENSOR_TABLE_ADDRESS (VM_MANAGER_AUDIO_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_MANAGER_VMIM_TABLE_ADDRESS (VM_MANAGER_SENSOR_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)

#define VM_DF_DataPackage_FilePath_ADDRESS (VM_MANAGER_VMIM_TABLE_ADDRESS + VM_MANAGER_TABLE_SIZE)
// 子项
#define VM_DF_DataPackage_In_File_Offset_ADDRESS (VM_DF_DataPackage_FilePath_ADDRESS + 512)
#define VM_DF_DataPackage_In_File_Length_ADDRESS (VM_DF_DataPackage_In_File_Offset_ADDRESS + 4)
#define VM_DF_DataPackage_loadType_ADDRESS (VM_DF_DataPackage_In_File_Length_ADDRESS + 4)

#define VM_Str_Tmp_ADDRESS (VM_DF_DataPackage_FilePath_ADDRESS + 1024)
// fixme 别的地方会修改VM_DreamFactory_DataPackage_ADDRESS范围的地址，所以给了10240空间，需要仔细检查
#define VM_DreamFactory_DataPackage_ADDRESS (VM_Str_Tmp_ADDRESS + 1024)
#define VM_DreamFactory_MemoryBlock_ADDRESS (VM_DreamFactory_DataPackage_ADDRESS + 10240)
#define VM_DreamFactoryResourceBuffer_ADDRESS (VM_DreamFactory_MemoryBlock_ADDRESS + 16)
#define VM_CURR_APP_INFO_ADDRESS (VM_DreamFactoryResourceBuffer_ADDRESS + VM_MANAGER_TABLE_SIZE)
#define VM_LOG_TRACE_ADDRESS (VM_CURR_APP_INFO_ADDRESS + 512)

// 0x4000000开始是函数实现地址
#define VM_MANAGER_FUNC_LIST_SIZE 0x400
#define VM_MANAGER_FUNC_LIST_ADDRESS (VM_FUNC_HK_TABLE_ADDRESS + 0)
#define VM_SYS_MANAGER_FUNC_LIST_ADDRESS (VM_MANAGER_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MEMORY_MANAGER_FUNC_LIST_ADDRESS (VM_SYS_MANAGER_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_GAMEOLD_FUNC_LIST_ADDRESS (VM_MEMORY_MANAGER_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_LCD_FUNC_LIST_ADDRESS (VM_MANAGER_GAMEOLD_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_FILEIO_FUNC_LIST_ADDRESS (VM_MANAGER_LCD_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_STDIO_FUNC_LIST_ADDRESS (VM_MANAGER_FILEIO_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_TIMER_FUNC_LIST_ADDRESS (VM_MANAGER_STDIO_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_CTRL_FUNC_LIST_ADDRESS (VM_MANAGER_TIMER_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_NETWORK_FUNC_LIST_ADDRESS (VM_MANAGER_CTRL_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_GAME_UTIL_FUNC_LIST_ADDRESS (VM_MANAGER_NETWORK_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_DF_ENGINE_FUNC_LIST_ADDRESS (VM_MANAGER_GAME_UTIL_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_BILLING_FUNC_LIST_ADDRESS (VM_MANAGER_DF_ENGINE_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_UCS2_FUNC_LIST_ADDRESS (VM_MANAGER_BILLING_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_SCREEN_FUNC_LIST_ADDRESS (VM_MANAGER_UCS2_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_DF_SCRIPT_FUNC_LIST_ADDRESS (VM_MANAGER_SCREEN_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_GAME_LCD_FUNC_LIST_ADDRESS (VM_MANAGER_DF_SCRIPT_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_NETAPP_FUNC_LIST_ADDRESS (VM_MANAGER_GAME_LCD_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_AUDIO_FUNC_LIST_ADDRESS (VM_MANAGER_NETAPP_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_SENSOR_FUNC_LIST_ADDRESS (VM_MANAGER_AUDIO_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_MANAGER_VMIM_FUNC_LIST_ADDRESS (VM_MANAGER_SENSOR_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)

#define VM_DF_PACK_FUNC_LIST_ADDRESS (VM_MANAGER_VMIM_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_SCREEN_isInQuit_ADDRESS (VM_DF_PACK_FUNC_LIST_ADDRESS + VM_MANAGER_FUNC_LIST_SIZE)
#define VM_SCREEN_nextSubTScreen_ADDRESS (VM_SCREEN_isInQuit_ADDRESS + 4)
#define VM_DF_GetFormatStringBuffer_ADDRESS (VM_SCREEN_nextSubTScreen_ADDRESS + 4)
#define VM_MF_MemoryBlock_FUNC_LIST_ADDRESS (VM_DF_GetFormatStringBuffer_ADDRESS + 64)

// ROM的3MB是程序退出点
#define PROGRAM_EXIT_ADDR ROM_ADDRESS + 1024 * 1024 * 3
#pragma once

#define u8 unsigned char
#define u16 unsigned short
#define u32 unsigned int
#define u64 unsigned long

#define MR_MOUSE_DOWN 1
#define MR_MOUSE_UP 2
#define MR_MOUSE_MOVE 3
#define MR_KEY_PRESS 4
#define MR_KEY_RELEASE 5
